name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/docker/library/python:3.9-slim
    steps:
      - run: echo "testing code"
      - run: make test